### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by niranjantechofficial** [nezbednik/5-Minute-IPTV#1]
brother i need to talk with you ..you have telegram?

**Comment by NezbednikSK** [comment]
Nope, but i got discord :D (johnsnickler#0813)

**Comment by niranjantechofficial** [comment]
brother you know how to stream Live cricket??i can scrap links from hotstar but here need drm player

**Comment by NezbednikSK** [comment]
No, i don't know. And even if i did it would be illegal.

**Comment by niranjantechofficial** [comment]
yes but need for just how to play drm content...hotstar have cookies,refferer,origin, how to add that headders...i know how to on apk but don't know on php...if possible forward anything you have
